/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vbuser_particulate_render_NativeBlockRenderer */

#ifndef _Included_com_vbuser_particulate_render_NativeBlockRenderer
#define _Included_com_vbuser_particulate_render_NativeBlockRenderer
#ifdef __cplusplus
extern "C" {
#endif
#undef com_vbuser_particulate_render_NativeBlockRenderer_DEBUG
#define com_vbuser_particulate_render_NativeBlockRenderer_DEBUG 1L
/*
 * Class:     com_vbuser_particulate_render_NativeBlockRenderer
 * Method:    updateMap
 * Signature: ([J)V
 */
JNIEXPORT void JNICALL Java_com_vbuser_particulate_render_NativeBlockRenderer_updateMap
  (JNIEnv *, jclass, jlongArray);

/*
 * Class:     com_vbuser_particulate_render_NativeBlockRenderer
 * Method:    clearVisibilityCache
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_vbuser_particulate_render_NativeBlockRenderer_clearVisibilityCache
  (JNIEnv *, jclass);

/*
 * Class:     com_vbuser_particulate_render_NativeBlockRenderer
 * Method:    visibleInMap
 * Signature: (DDDDDD)Z
 */
JNIEXPORT jboolean JNICALL Java_com_vbuser_particulate_render_NativeBlockRenderer_visibleInMap
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
